/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package siperka.view;

/**
 *
 * @author Kariema
 */
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import siperka.controll.User_controller;

public class login extends javax.swing.JFrame {

     V_jampit dashboard = new V_jampit();
    public login() {
        initComponents();
        setTitle("SIPERKA");
    }

    public void addLoginListener(MouseListener e){
        this.btn_login.addMouseListener(e);
        login.addMouseListener(e);
    }
    
    public String getUsername(){
        return this.username.getText();
    }
    
    public String getPassword(){
        return this.password.getText();
    }
    
    public void setMessages(String s){
        this.messages.setText(s);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        messages = new javax.swing.JLabel();
        murup = new javax.swing.JLabel();
        mati = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        login = new javax.swing.JLabel();
        btn_login = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setLocation(new java.awt.Point(333, 144));
        setMinimumSize(new java.awt.Dimension(720, 480));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        messages.setBackground(new java.awt.Color(255, 51, 102));
        messages.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        messages.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(messages, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 380, 240, 20));

        murup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Untitled-2.png"))); // NOI18N
        murup.setText("jLabel2");
        murup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        murup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                murupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                murupMouseExited(evt);
            }
        });
        getContentPane().add(murup, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, 30, 30));

        mati.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Untitled-1.png"))); // NOI18N
        mati.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mati.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                matiMouseClicked(evt);
            }
        });
        getContentPane().add(mati, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, -1, 30));

        username.setBackground(new java.awt.Color(204, 204, 204));
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 270, 40));

        password.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 270, 40));

        login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/login.png"))); // NOI18N
        login.setText("jLabel3");
        login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginMouseExited(evt);
            }
        });
        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 110, 30));

        btn_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/login1.png"))); // NOI18N
        btn_login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 110, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/home.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseEntered

    private void murupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_murupMouseEntered
        murup.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_murupMouseEntered

    private void murupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_murupMouseExited
        murup.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_murupMouseExited

    private void matiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_matiMouseClicked
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_matiMouseClicked

    private void loginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseEntered
    login.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_loginMouseEntered

    private void loginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseExited
    login.setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_loginMouseExited

     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel login;
    private javax.swing.JLabel mati;
    private javax.swing.JLabel messages;
    private javax.swing.JLabel murup;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
