/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package siperka.view;

import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import java.sql.SQLException;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import siperka.controll.bibit_controller;
import siperka.model.Lahan;
import siperka.model.Pupuk;
import siperka.model.Tanaman;
import siperka.model.Panen;
import siperka.model.Tanaman;

public class V_jampit extends javax.swing.JFrame {

    private int n = 1;

    public V_jampit() {
        initComponents();
        lahan.setVisible(false);
        bibit.setVisible(false);
        pupuk.setVisible(false);
        tanaman.setVisible(false);
        gudang.setVisible(false);
        panen.setVisible(false);
        kebun1.setVisible(false);

        kebun2.setVisible(false);

    }

    public void addUSerListener(MouseListener e) {
        this.addUser.addMouseListener(e);
    }

    public void addPanenListener(MouseListener e) {
        this.btn_panen.addMouseListener(e);
    }

    public void bibit(MouseListener listener) {
        btn_bibit.addMouseListener(listener);
    }

    public void Disable() {

    }

    public void addButtonKebun(MouseListener e) {
        kebun2.addMouseListener(e);
    }

    public void addButtonPanen(MouseListener e) {
        btn_panen.addMouseListener(e);
    }

    public void addButtonTanaman(MouseListener e) {
        btn_tanaman.addMouseListener(e);
    }

    public void addButtonBibit(MouseListener e) {
        btn_bibit.addMouseListener(e);
    }

    public void addButtonPupuk(MouseListener e) {
        btn_pupuk.addMouseListener(e);
    }

    public void addButtonGudang(MouseListener e) {
        btn_gudang.addMouseListener(e);
    }

    public void addButtonLahan(MouseListener e) {
        btn_lahan.addMouseListener(e);
    }

    public void addButtonAddUser(MouseListener e) {
        addUser.addMouseListener(e);
    }

    public void addButtonLogin(MouseListener e) {
        jLabel3.addMouseListener(e);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        about = new javax.swing.JLabel();
        btn_bibit = new javax.swing.JLabel();
        bibit = new javax.swing.JLabel();
        btn_gudang = new javax.swing.JLabel();
        gudang = new javax.swing.JLabel();
        btn_lahan = new javax.swing.JLabel();
        btn_tanaman = new javax.swing.JLabel();
        tanaman = new javax.swing.JLabel();
        lahan = new javax.swing.JLabel();
        btn_panen = new javax.swing.JLabel();
        panen = new javax.swing.JLabel();
        btn_pupuk = new javax.swing.JLabel();
        pupuk = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        exit1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lanjut = new javax.swing.JLabel();
        kembali = new javax.swing.JLabel();
        halaman = new javax.swing.JLabel();
        kebun1 = new javax.swing.JLabel();
        kebun2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        addUser = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setLocation(new java.awt.Point(333, 144));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        about.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        about.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutMouseClicked(evt);
            }
        });
        getContentPane().add(about, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 70, 20));

        btn_bibit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/bibit11.png"))); // NOI18N
        btn_bibit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_bibit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_bibitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_bibitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_bibitMouseExited(evt);
            }
        });
        getContentPane().add(btn_bibit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 100, 110));

        bibit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/bibit12.png"))); // NOI18N
        bibit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bibitMouseClicked(evt);
            }
        });
        getContentPane().add(bibit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 100, 110));

        btn_gudang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/gudang11.png"))); // NOI18N
        btn_gudang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_gudang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_gudangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_gudangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_gudangMouseExited(evt);
            }
        });
        getContentPane().add(btn_gudang, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 100, 110));

        gudang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/gudang12.png"))); // NOI18N
        gudang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(gudang, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 100, 110));

        btn_lahan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/lahan11.PNG"))); // NOI18N
        btn_lahan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_lahan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_lahanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_lahanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_lahanMouseExited(evt);
            }
        });
        getContentPane().add(btn_lahan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 100, 110));

        btn_tanaman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/tanaman11.png"))); // NOI18N
        btn_tanaman.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_tanaman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_tanamanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_tanamanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_tanamanMouseExited(evt);
            }
        });
        getContentPane().add(btn_tanaman, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 100, 110));

        tanaman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/tanaman12.png"))); // NOI18N
        tanaman.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(tanaman, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 100, 110));

        lahan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/lahan12.PNG"))); // NOI18N
        lahan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(lahan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 100, 110));

        btn_panen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/panen11.png"))); // NOI18N
        btn_panen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_panen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_panenMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_panenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_panenMouseExited(evt);
            }
        });
        getContentPane().add(btn_panen, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 100, 110));

        panen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/panen12.png"))); // NOI18N
        panen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(panen, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 100, 110));

        btn_pupuk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pupuk11.png"))); // NOI18N
        btn_pupuk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_pupuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_pupukMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_pupukMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_pupukMouseExited(evt);
            }
        });
        getContentPane().add(btn_pupuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 100, 110));

        pupuk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pupuk12.png"))); // NOI18N
        pupuk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(pupuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 100, 110));

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/exit.png"))); // NOI18N
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseExited(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, 30, 30));

        exit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/exit2.png"))); // NOI18N
        exit1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit1MouseClicked(evt);
            }
        });
        getContentPane().add(exit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, 30, 30));

        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, 60, 20));

        lanjut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/lanjut.png"))); // NOI18N
        lanjut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lanjut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lanjutMouseEntered(evt);
            }
        });
        getContentPane().add(lanjut, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 300, -1, -1));

        kembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/kembali.png"))); // NOI18N
        kembali.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                kembaliMouseEntered(evt);
            }
        });
        getContentPane().add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, -1, -1));

        halaman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/siperka/view/halaman1.png"))); // NOI18N
        getContentPane().add(halaman, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, -1, -1));

        kebun1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/kebun1.png"))); // NOI18N
        kebun1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kebun1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                kebun1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                kebun1MouseExited(evt);
            }
        });
        getContentPane().add(kebun1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 80, 30));

        kebun2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/kebun2.png"))); // NOI18N
        kebun2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kebun2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kebun2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                kebun2MouseExited(evt);
            }
        });
        getContentPane().add(kebun2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, -1, 30));

        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel13MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel13MouseExited(evt);
            }
        });
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 4, 70, 20));

        addUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addUserMouseClicked(evt);
            }
        });
        getContentPane().add(addUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 80, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/PBO.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, -1));

        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 70, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_bibitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_bibitMouseEntered
        bibit.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btn_bibitMouseEntered

    private void btn_bibitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_bibitMouseExited
        bibit.setVisible(false);         // TODO add your handling code here:
    }//GEN-LAST:event_btn_bibitMouseExited

    private void btn_tanamanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tanamanMouseEntered
        tanaman.setVisible(true);          // TODO add your handling code here:
    }//GEN-LAST:event_btn_tanamanMouseEntered

    private void btn_tanamanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tanamanMouseExited
        tanaman.setVisible(false);          // TODO add your handling code here:
    }//GEN-LAST:event_btn_tanamanMouseExited

    private void btn_panenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_panenMouseEntered
        panen.setVisible(true);          // TODO add your handling code here:
    }//GEN-LAST:event_btn_panenMouseEntered

    private void btn_panenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_panenMouseExited
        panen.setVisible(false);          // TODO add your handling code here:
    }//GEN-LAST:event_btn_panenMouseExited

    private void btn_gudangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_gudangMouseEntered
        gudang.setVisible(true);          // TODO add your handling code here:
    }//GEN-LAST:event_btn_gudangMouseEntered

    private void btn_gudangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_gudangMouseExited
        gudang.setVisible(false);          // TODO add your handling code here:
    }//GEN-LAST:event_btn_gudangMouseExited

    private void btn_pupukMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pupukMouseEntered
        pupuk.setVisible(true);          // TODO add your handling code here:
    }//GEN-LAST:event_btn_pupukMouseEntered

    private void btn_pupukMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pupukMouseExited
        pupuk.setVisible(false);          // TODO add your handling code here:
    }//GEN-LAST:event_btn_pupukMouseExited

    private void exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseEntered
        exit.setVisible(false);          // TODO add your handling code here:
    }//GEN-LAST:event_exitMouseEntered

    private void exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseExited
        exit.setVisible(true);     // TODO add your handling code here:
    }//GEN-LAST:event_exitMouseExited

    private void exit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit1MouseClicked
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_exit1MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    private void lanjutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lanjutMouseEntered

        n++;
        if (n == 5) {
            n = 1;
        }
        halaman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/siperka/view/halaman" + n + ".png")));
        // NOI18N
    }//GEN-LAST:event_lanjutMouseEntered

    private void kembaliMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kembaliMouseEntered

        n--;
        if (n == 0) {
            n = 4;
        }
        halaman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/siperka/view/halaman" + n + ".png")));


    }//GEN-LAST:event_kembaliMouseEntered

    private void btn_panenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_panenMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_panenMouseClicked


    private void btn_bibitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_bibitMouseClicked

    }//GEN-LAST:event_btn_bibitMouseClicked

    private void btn_tanamanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tanamanMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_tanamanMouseClicked

    private void btn_pupukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pupukMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_pupukMouseClicked

    private void btn_gudangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_gudangMouseClicked

    }//GEN-LAST:event_btn_gudangMouseClicked

    private void btn_lahanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_lahanMouseExited
        lahan.setVisible(false);          // TODO add your handling code here:
    }//GEN-LAST:event_btn_lahanMouseExited

    private void btn_lahanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_lahanMouseEntered
        lahan.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btn_lahanMouseEntered

    private void btn_lahanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_lahanMouseClicked

    }//GEN-LAST:event_btn_lahanMouseClicked

    private void kebun1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kebun1MouseEntered
        kebun1.setVisible(false);
        kebun2.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_kebun1MouseEntered

    private void kebun1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kebun1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_kebun1MouseExited

    private void kebun2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kebun2MouseExited
        // TODO add your handling code here:
        kebun2.setVisible(false);
        kebun1.setVisible(true);
    }//GEN-LAST:event_kebun2MouseExited

    private void jLabel13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseEntered
        kebun1.setVisible(true);
        kebun2.setVisible(true);

    }//GEN-LAST:event_jLabel13MouseEntered

    private void jLabel13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseExited
        kebun1.setVisible(false);
        kebun2.setVisible(false);

    }//GEN-LAST:event_jLabel13MouseExited

    private void bibitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bibitMouseClicked

    }//GEN-LAST:event_bibitMouseClicked

    private void addUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addUserMouseClicked

    }//GEN-LAST:event_addUserMouseClicked

    private void kebun2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kebun2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_kebun2MouseClicked

    private void aboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutMouseClicked
        this.setVisible(false);
        siperka.view.about n = new siperka.view.about();// TODO add your handling code here:
        n.setVisible(true);
        n.setLevel(1);
    }//GEN-LAST:event_aboutMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel about;
    private javax.swing.JLabel addUser;
    private javax.swing.JLabel bibit;
    private javax.swing.JLabel btn_bibit;
    private javax.swing.JLabel btn_gudang;
    private javax.swing.JLabel btn_lahan;
    private javax.swing.JLabel btn_panen;
    private javax.swing.JLabel btn_pupuk;
    private javax.swing.JLabel btn_tanaman;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel exit1;
    private javax.swing.JLabel gudang;
    private javax.swing.JLabel halaman;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel kebun1;
    private javax.swing.JLabel kebun2;
    private javax.swing.JLabel kembali;
    private javax.swing.JLabel lahan;
    private javax.swing.JLabel lanjut;
    private javax.swing.JLabel panen;
    private javax.swing.JLabel pupuk;
    private javax.swing.JLabel tanaman;
    // End of variables declaration//GEN-END:variables
}
